module.exports = [
    {
        provider: 'carto',
        datasetId: '0b9f0100-ce5b-430f-ad8f-3363efa05481',
        tableName: 'edi',
        slug: 'Environmental-Democracy-Index-1490086842552',
        aggregateColumn: 'AVG(overall_score)',
        stringColumn: 'region',
        numericColumn: 'overall_score',
        numericColumn2: 'justice_pillar_score',
        whereLowerValue: 2,
        whereEqValue: 2.1,
        whereGreaterValue: 2.2,
        whereLowerValue2: 1,
        whereLikeValue: '\'Europ%\'',
    },
    {
        provider: 'document',
        datasetId: '9be3bf63-97fc-4bb0-b913-775ccae3cf9e',
        tableName: 'index_9be3bf6397fc4bb0b913775ccae3cf9e_1574354150743',
        slug: 'Glad-Alerts-Daily-Geostore-User-Areas_3',
        aggregateColumn: 'AVG(alert__count)',
        stringColumn: 'bra_biome__name',
        numericColumn: 'alert__count',
        numericColumn2: 'alert_area__ha',
        whereLowerValue: 2,
        whereEqValue: 5,
        whereGreaterValue: 8,
        whereLowerValue2: 0.1,
        whereLikeValue: '\'Amaz%\'',
    }
];
